parameters:
  - name: DeploymentStage
    displayName: Deployment Stage
    type: string
    default: dev
    values:
      - dev
      - stg
      - uat
      - prod

trigger:
  branches:
    include:
      - none

pool:
  vmImage: 'windows-latest'

variables:
  - group: upbiinbound-${{ upper(parameters.DeploymentStage) }}
  - name: resourceTemplateFile
    value: "./infrastructure/bicep/dbx.bicep"
  - name: resourceParamsFile
    value: "./infrastructure/parameters/dbx-upbi.params.json"
  - name: deploymentStage
    value: ${{ lower(parameters.DeploymentStage) }}
  - name: groupsFile
    value: "./infrastructure/parameters/dbw-upbi-groups.params.json"

name: 'Branch $(Build.SourceBranchName) to DeploymentStage $(deploymentStage)'

jobs:
  - job: DeployDbw
    displayName: Deploy Databricks Workspace
    steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'sc-upbi-microsoft-partner-network'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az deployment group create \
              --resource-group rg-eu2-latam-poc-mlops-${{ parameters.DeploymentStage }}-001 \
              --template-file ./infrastructure/bicep/dbw.bicep \
              --parameters @./infrastructure/parameters/dbw-upbi.params.json \
              --mode Incremental

  