trigger:
  branches:
    include:
      - none

pool:
  vmImage: 'ubuntu-latest'

variables:
  AZURE_SUBSCRIPTION_ID: '5c052e51-795d-4106-84cb-5dec482214e0'
  RESOURCE_GROUP_NAME: 'rg-eu2-latam-poc-mlops-dev-001'
  LOCATION: 'eastus2'
  TEMPLATE_FILE: 'main.bicep'
  PARAMETERS_FILE: 'dbx-upbi.params'

stages:
  - stage: CreateResourceGroupAndDeploy
    jobs:
      - job: DeploymentJob
        steps:

        # Passo 1: Fazer login no Azure CLI
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'AzureServiceConnection'  # Nome atualizado da conexão de serviço
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              echo "Log in to Azure"
              az account set --subscription $(AZURE_SUBSCRIPTION_ID)

        # Passo 2: Criar o grupo de recursos (se não existir)
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'AzureServiceConnection'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              echo "Criando grupo de recursos"
              az group create --name $(RESOURCE_GROUP_NAME) --location $(LOCATION)

        # Passo 3: Fazer o deployment do template Bicep
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'AzureServiceConnection'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              echo "Fazendo o deployment do template Bicep"
              az deployment group create \
                --resource-group $(RESOURCE_GROUP_NAME) \
                --template-file $(TEMPLATE_FILE) \
                --parameters $(PARAMETERS_FILE)
