name: Deploy Bicep

on:
  push:
    branches:
      - main  # Ou a branch que você deseja monitorar

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          clientId: ${{ secrets.AZURE_CLIENT_ID }}
          clientSecret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenantId: ${{ secrets.AZURE_TENANT_ID }}
          