name: 'chatbotfull'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest
    strategy:
      matrix:
        deploymentStage: [dev, stg, uat, prod]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Variables
        id: vars
        run: |
          echo "resourceTemplateFileSt=./infrastructure/bicep/st.bicep" >> $GITHUB_ENV
          echo "resourceParamsFileSt=./infrastructure/parameters/st-upbi.params.json" >> $GITHUB_ENV
          echo "resourceTemplateFileCv=./infrastructure/bicep/cv.bicep" >> $GITHUB_ENV
          echo "resourceParamsFileCv=./infrastructure/parameters/cv-upbi.params.json" >> $GITHUB_ENV
          echo "resourceParamsFilesSrch=./infrastructure/parameters/srch-upbi.params.json" >> $GITHUB_ENV
          echo "resourceTemplateFilesSrch=./infrastructure/bicep/srch.bicep" >> $GITHUB_ENV
          echo "resourceParamsFilesMap=./infrastructure/parameters/map-upbi.params.json" >> $GITHUB_ENV
          echo "resourceTemplateFileMap=./infrastructure/bicep/map.bicep" >> $GITHUB_ENV
          echo "resourceParamsFilesSs=./infrastructure/parameters/ss-upbi.params.json" >> $GITHUB_ENV
          echo "resourceTemplateFilesSs=./infrastructure/bicep/ss.bicep" >> $GITHUB_ENV
          echo "resourceParamsFilesOia=./infrastructure/parameters/oia-upbi.params.json" >> $GITHUB_ENV
          echo "resourceTemplateFilesOia=./infrastructure/bicep/oia.bicep" >> $GITHUB_ENV
          echo "resourceTemplateFilesApp=./infrastructure/bicep/app.bicep" >> $GITHUB_ENV
          echo "resourceParamsFilesApp=./infrastructure/parameters/app-upbi.params.json" >> $GITHUB_ENV
          echo "resourceTemplateFilesApplan=./infrastructure/bicep/applan.bicep" >> $GITHUB_ENV
          echo "resourceParamsFilesApplan=./infrastructure/parameters/applan-upbi.params.json" >> $GITHUB_ENV
          echo "resourceTemplateFilesApim=./infrastructure/bicep/apim.bicep" >> $GITHUB_ENV
          echo "resourceParamsFilesApim=./infrastructure/parameters/apim-upbi.params.json" >> $GITHUB_ENV
          echo "resourceTemplateFileDbw=./infrastructure/bicep/dbw.bicep" >> $GITHUB_ENV
          echo "resourceParamsFileDbw=./infrastructure/parameters/dbw-upbi.params.json" >> $GITHUB_ENV
          echo "resourceTemplateFileSynw=./infrastructure/bicep/synw.bicep" >> $GITHUB_ENV
          echo "resourceParamsFileSynw=./infrastructure/parameters/synw-upbi.params.json" >> $GITHUB_ENV
          echo "githubOrganizationName=PedroCarvalho18" >> $GITHUB_ENV
          echo "githubRepositoryName=chatbot" >> $GITHUB_ENV
          echo "deploymentStage=${{ matrix.deploymentStage }}" >> $GITHUB_ENV

      - name: Create Azure AD Application and Federated Credential
        run: |
          applicationRegistrationDetails=$(az ad app create --display-name 'chatbot')
          applicationRegistrationObjectId=$(echo $applicationRegistrationDetails | jq -r '.id')
          applicationRegistrationAppId=$(echo $applicationRegistrationDetails | jq -r '.appId')

          az ad app federated-credential create \
            --id $applicationRegistrationObjectId \
            --parameters "{\"name\":\"chatbot\",\"issuer\":\"https://token.actions.githubusercontent.com\",\"subject\":\"repo:${{ env.githubOrganizationName }}/${{ env.githubRepositoryName }}:ref:refs/heads/main\",\"audiences\":[\"api://AzureADTokenExchange\"]}"

      - name: Deploy Stage
        run: |
          # Template deployment commands for each stage
          az deployment group create --resource-group rg-eu2-latam-poc-mlops-${{ env.deploymentStage }}-001 --template-file ${{ env.resourceTemplateFileSt }} --parameters @${{ env.resourceParamsFileSt }}
          # Repeat for other templates and parameters as needed

 