name: chatbot

on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read

env:
  AZURE_RESOURCEGROUP_NAME: chatbot
  ENVIRONMENT: nonprod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Create Azure AD Application and Federated Credential
        run: |
          $applicationRegistration = New-AzADApplication -DisplayName 'chatbot'
          New-AzADAppFederatedCredential `
            -Name 'chatbot' `
            -ApplicationObjectId $applicationRegistration.Id `
            -Issuer 'https://token.actions.githubusercontent.com' `
            -Audience 'api://AzureADTokenExchange' `
            -Subject "repo:PedroCarvalho18/chatbot:ref:refs/heads/main"
        shell: pwsh
      
     