name: 'Deploy API Management to ${{ github.ref_name }}'

on:
  push:
    branches:
      - main

jobs:
  DeployApim:
    runs-on: windows-latest

    env:
      deploymentStage: dev  # Substitua conforme necessário ou defina variáveis de ambiente no GitHub.
      resourceTemplateFile: "./infrastructure/bicep/apim.bicep"
      resourceParamsFile: "./infrastructure/parameters/apim-upbi.params.json"
      resourceGroupName: "rg-eu2-latam-poc-mlops-${{ env.deploymentStage }}-001"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Git checkout for infrastructure and YAML files
        run: |
          git checkout main
          ls infrastructure yaml

      - name: Update settings files
        run: |
          echo "Updating settings files"
          # Adicione seu script ou comando para atualizar arquivos de configuração
          # Certifique-se de que isso está alinhado com seu processo
          echo "Subscription: sc-upbi-microsoft-partner-network"
          echo "Deployment Stage: ${{ env.deploymentStage }}"

      - name: Deploy Resource Group
        run: |
          echo "Deploying resource group"
          echo "Using resource group: ${{ env.resourceGroupName }}"
          echo "Using template file: ${{ env.resourceTemplateFile }}"
          echo "Using parameters file: ${{ env.resourceParamsFile }}"
          # Aqui você chamaria os comandos apropriados para a implementação de infra, como:
          # az deployment group create --resource-group ${{ env.resourceGroupName }} --template-file ${{ env.resourceTemplateFile }} --parameters ${{ env.resourceParamsFile }}
