name: 'DeployAppplan'

on:
  push:
    branches:
      - main

jobs:
  DeployAppPlan:
    runs-on: windows-latest

    env:
      deploymentStage: dev  # Defina como dev, stg, uat ou prod conforme necessário
      resourceTemplateFile: "./infrastructure/bicep/applan.bicep"
      resourceParamsFile: "./infrastructure/parameters/applan-upbi.params.json"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Git checkout for infrastructure and YAML files
        run: |
          git checkout main
          ls infrastructure yaml

      - name: Update settings files
        run: |
          echo "Updating settings files"
          echo "Subscription: sc-upbi-microsoft-partner-network"
          echo "Deployment Stage: ${{ env.deploymentStage }}"

      - name: Deploy Resource Group
        run: |
          echo "Deploying resource group"
          echo "Using resource group: rg-eu2-latam-poc-mlops-${{ env.deploymentStage }}-001"
          echo "Using template file: ${{ env.resourceTemplateFile }}"
          echo "Using parameters file: ${{ env.resourceParamsFile }}"
          # az deployment group create --resource-group rg-eu2-latam-poc-mlops-${{ env.deploymentStage }}-001 --template-file ${{ env.resourceTemplateFile }} --parameters ${{ env.resourceParamsFile }}
