parameters:
  - name: deploymentStage
    displayName: Deployment Stage
    type: string
    default: dev
    values:
      - dev
      - stg
      - uat
      - prod

trigger:
  branches:
    include:
      - none

pool:
  vmImage: windows-latest

jobs:
  - job: CleanUp
    displayName: Clean Up Resources
    steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'sc-upbi-microsoft-partner-network'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            resources=$(az resource list --resource-group rg-eu2-latam-poc-mlops-${{ parameters.deploymentStage }}-001 --query "[].{name:name, type:type}" -o json)

            for row in $(echo "${resources}" | jq -c '.[]'); do
              resourceName=$(echo "$row" | jq -r '.name')
              resourceType=$(echo "$row" | jq -r '.type')
              echo "Deleting resource: $resourceName of type $resourceType"
              
              if [[ "$resourceType" == "Microsoft.CognitiveServices/accounts" ]]; then
                az resource delete --name "$resourceName" --resource-group rg-eu2-latam-poc-mlops-${{ parameters.deploymentStage }}-001 --resource-type "$resourceType" --api-version 2023-10-01-preview
              else
                az resource delete --name "$resourceName" --resource-group rg-eu2-latam-poc-mlops-${{ parameters.deploymentStage }}-001 --resource-type "$resourceType"
              fi
            done
