name: Deploy CV

on:
  workflow_dispatch: # Permite executar manualmente o workflow
  push:
    branches:
      - main # Ou outra branch que você desejar

jobs:
  DeployCv:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up parameters
        id: params
        run: |
          echo "deploymentStage=${{ github.event.inputs.deploymentStage || 'dev' }}" >> $GITHUB_ENV
          echo "resourceTemplateFile=./infrastructure/bicep/cv.bicep" >> $GITHUB_ENV
          echo "resourceParamsFile=./infrastructure/parameters/cv-upbi.params.json" >> $GITHUB_ENV
          echo "resourceGroupName=rg-eu2-latam-poc-mlops-${{ env.deploymentStage }}-001" >> $GITHUB_ENV

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # Usando o JSON com credenciais

      - name: Update settings files
        run: |
          # Execute a script or command to update settings files here
          echo "Updating settings files with deployment stage: ${{ env.deploymentStage }}"
          # Exemplo: bash update_settings.sh ${{ env.resourceParamsFile }} ${{ env.deploymentStage }}

      - name: Deploy resources
        run: |
          echo "Deploying resources..."
          az deployment group create --resource-group ${{ env.resourceGroupName }} --template-file ${{ env.resourceTemplateFile }} --parameters @$resourceParamsFile
