parameters:
  - name: deploymentStage
    displayName: Deployment Stage
    type: string
    default: dev
    values:
      - dev
      - stg
      - uat
      - prod

trigger:
  branches:
    include:
      - none

pool:
  vmImage: windows-latest

variables:
  - group: upbiinbound-${{ upper(parameters.deploymentStage) }}
  - name: resourceParamsFilesSrch
    value: "./infrastructure/parameters/srch-upbi.params.json"
  - name: resourceTemplateFileSrch
    value: "./infrastructure/bicep/srch.bicep"
  - name: deploymentStage
    value: ${{ lower(parameters.deploymentStage) }}

name: 'Branch $(Build.SourceBranchName) to DeploymentStage $(deploymentStage)'

jobs:
  - job: DeploySrch
    steps:
      - checkout: none   
      - template: modules/gitcheckout.yml
        parameters:
          folders: "infrastructure yaml"
      - template: modules/settingsfilesupdate.yml
        parameters:
          subscriptionName: sc-upbi-microsoft-partner-network
          settingsFiles: 
            $(resourceParamsFile)
          params:
            DeploymentStage: $(deploymentStage)
    
      - template: modules/resourcegroupdeployment.yml
        parameters:
          subscriptionName: sc-upbi-microsoft-partner-network #"Microsoft Partner Network"
          resourceGroupName: rg-eu2-latam-poc-mlops-$(deploymentStage)-001
          templateFile: $(resourceTemplateFileSrch)
          templateParamsFile: $(resourceParamsFileSrch)
          params:
            DeploymentStage: $(deploymentStage)

